### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DavidFeria01** [SistemasTecTlaxiaco/infografia-DavidFeria01-1#2]
![_Infografías](https://user-images.githubusercontent.com/79876872/133126011-8cd1e4f0-a4ab-4f24-9c43-53e49c39e2a3.jpg)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo, faltan las referencias bibliográficas.
Calificación: 19%

**Comment by josealfredo79** [comment]
y tambien faltan las metodologías y herramientas, bien hecho y revisado
